# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 12:46
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ClassificationTree')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.CharField(default='', max_length=256)),
                ('paper_page', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('publish_time', models.DateTimeField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('hash_code', models.CharField(max_length=64)),
                ('author', models.ManyToManyField(to='backend.Author')),
                ('classification_tree_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ClassificationTree')),
                ('log', models.ManyToManyField(to='backend.Log')),
                ('notes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Note')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('head_img', models.ImageField(upload_to='')),
                ('classification_tree_root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ClassificationTree')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Log')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
